#define HLLC_1 1
#define PARENT_MESH_LEVEL 7
#define AMR 0
#define IDEAL_GAS 1
#define TRANSMISSIVE 1
#define WAVESPEED_ENTHALPY 1
#define X_MAX 1.0
#define Y_MAX 1.0
#define Z_MAX 1.0
#define CFL 0.5
#define GAMMA 1.4
#define SIMULATION_TIME 0.15
